### ISSUE TITLE
lowRISC: Software Trace

### ISSUE THREAD

**Issue by wallento** [opensocdebug/hardware#7]
For a first prototype we need the Rocket core to emit the execution information it currently plots also on pins. We also need to add a CSR.

We need a small module then that generates (`id`, `value`, `enable`) from it.

Finally the generic STM performs the packetization of it.

**Comment by wsong83** [comment]
Seems only one assignee. I am going to do it but still not sure about how to packetizate it.

**Comment by wallento** [comment]
Yeah, this one assignee sucks.

We can split it like this:

 * Rocket changes (Wei)
 * STM Module (Stefan)
 * Trace combiner (signals to value,id,enable), unassigned

At least for the prototyping now the STM Module is probably best done in SV, while the trace combiner can be Chisel or SV I think.

**Comment by wallento** [comment]
## Trace Combiner

Combines low level core signals to a trace event

## Inputs

 * The $display trace data from Rocket
 * write to a new CSR

## Output

 * id
 * value
 * enable
